var canvas=document.getElementById("canvas");

engine.Core.initialize(canvas);
var cw=canvas.width;
var ch=canvas.height;
var scene=new engine.Scene();
scene.lightManager.setAmbientIntensity(.1);
var camera=new engine.Camera();
camera.setScale(cw,ch);
camera.setViewport(0,0,cw,ch);
camera.bgColor=[1,1,1];
var miniCamera=new engine.Camera();
miniCamera.setScale(600,600);
miniCamera.setPosition(0,0);
miniCamera.setViewport(500,0,300,300);
miniCamera.bgColor=[0.1,0.2,0.5];

var bg=new engine.Rectangle();
bg.setScale(cw,ch);
bg.color=[1,1,1];
var light=new engine.Light();
light.setPosition(0,300);
light.near=20;
light.far=50;
light.intensity=0.9;
light.color=[1,0,1.0];
var light2=new engine.Light();
light2.near=10;
light2.far=30;
light2.intensity=3;
light2.color=[0,0,1];
var light3=new engine.Light();
light3.setPosition(0,-30);
light3.near=10;
light3.far=30;
light3.intensity=1;
light3.color=[1,0,0];
var object=new engine.Rectangle();
object.setScale(cw/5, cw/5);
object.color=[0.4,0,0];
var object2=new engine.Rectangle();
object2.setPosition(900,0);
object2.setScale(cw/5,ch/5);
object2.color=[0,0,0];
var macaco=new engine.Texture("Img/monkey.png");
var sprite=new engine.Sprite(macaco);
sprite.setPosition(0,0);
sprite.setScale(cw/7, cw/7);
scene.addObject(camera);
scene.addObject(miniCamera);
scene.addObject(bg);
scene.addObject(object);
scene.addObject(object2);
scene.addObject(sprite);
scene.addObject(light);
scene.addObject(light2);
scene.addObject(light3);
engine.setScene(scene);
var t=0;
light.setPosition(0,0);
scene.update=function(){
light.setPosition(light.getPosition().x+1,light.getPosition().y);
miniCamera.setPosition(light.getPosition().x,light.getPosition().y);
object.setRotation(object.getRotation()-0.1);
};